dist: xenial

language: go
go:
  - 1.12

branches:
  only:
    - master

# this downloads and unpacks netlifyctl
before_install:
  - npm install netlify-cli -g

# Skip the install step (go get ./...). We use modules and "go get" fails.
install: true

script:
  - ./s/travis_build.sh
