language: go
go:
  - "1.10"

branches:
  only:
    - master

# https://github.com/GoogleCloudPlatform/golang-samples/blob/master/.travis.yml
before_cache:
  - rm -rf $GOPATH/src/github.com/essentialbooks
  - rm -rf $GOPATH/pkg/**/github.com/essentialbooks

cache:
  directories:
    - $GOPATH/src
    - $GOPATH/pkg

before_install:
  - pushd $GOPATH/pkg; wget https://github.com/netlify/netlifyctl/releases/download/v0.3.2/netlifyctl-linux-amd64-0.3.2.tar.gz; tar -xvf netlifyctl-linux-amd64-0.3.2.tar.gz; popd

install:
  - ./s/travis_install.sh

script:
  - ./s/travis_build.sh
